export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.local/cache"

if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

#brew:eval "$(/opt/homebrew/bin/brew shellenv)"

ZINIT_HOME="${XDG_DATA_HOME:-${HOME}/.local/share}/zinit/zinit.git"
source "${ZINIT_HOME}/zinit.zsh"

zinit ice depth=1; zinit light romkatv/powerlevel10k
zinit light zsh-users/zsh-syntax-highlighting
zinit light zsh-users/zsh-completions
zinit light zsh-users/zsh-autosuggestions
#fzf:zinit light Aloxaf/fzf-tab
zinit snippet OMZP::git
zinit snippet OMZP::sudo
zinit snippet OMZP::gpg-agent
zinit snippet OMZP::kubectl
zinit snippet OMZP::command-not-found

# Load completions
autoload -Uz compinit && compinit

zinit cdreplay -q

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

# Keybindings
bindkey -e
bindkey '^p' history-search-backward
bindkey '^n' history-search-forward
bindkey '^[w' kill-region
bindkey '^[[H' beginning-of-line
bindkey '^[[F' end-of-line
bindkey '^[[3~' delete-char

# History
HISTSIZE=5000
HISTFILE=~/.config/env/history
SAVEHIST=$HISTSIZE
HISTDUP=erase
setopt appendhistory
setopt sharehistory
setopt hist_ignore_space
setopt hist_ignore_all_dups
setopt hist_save_no_dups
setopt hist_ignore_dups
setopt hist_find_no_dups

# Completion styling
zstyle ':completion:*' matcher-list 'm:{a-z}={A-Za-z}'
zstyle ':completion:*' list-colors "${(s.:.)LS_COLORS}"
zstyle ':completion:*' menu no
#fzf:zstyle ':fzf-tab:complete:cd:*' fzf-preview 'ls --color $realpath'
#fzf:zstyle ':fzf-tab:complete:__zoxide_z:*' fzf-preview 'ls --color $realpath'

# Aliases
#eza:alias ls="eza -a --sort=name --group-directories-first"
#nvim:alias vim='nvim'
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias week="date +%V"

export PATH="$PATH:$HOME/.local/bin"
#cargo:export PATH="$PATH:$HOME/.cargo/bin"
#composer:export PATH="$PATH:$HOME/.composer/vendor/bin"
#go:export GOPATH="$HOME/.local/go"


# Shell integrations
#fzf:eval "$(fzf --zsh)"
#zoxide:eval "$(zoxide init zsh)"

function perform_maintenance_update {
    set -x
#apt:    sudo apt update && sudo apt upgrade -y
#snap:    sudo snap refresh
#dnf:    sudo dnf check-update && sudo dnf upgrade -y
#brew:    brew update && brew upgrade
#rustup:    rustup update
#cargo:    cargo install-update -a
#composer:    composer g update
    zinit self-update
    zinit update --all --parallel
}