.check-dependency-sudo:
	@command -v sudo > /dev/null

.install-dependencies: .check-dependency-sudo
	@sudo apt install ruby php git zsh -y

.install-tools:
	@echo 1

install: .install-dependencies
	@echo 1
