.check-dependency-sudo:
	@command -v sudo > /dev/null

.install-dependencies: .check-dependency-sudo
	@sudo apt install ruby php git zsh -y

install-tools:
	@sudo apt install jq tmux -y

install: .install-dependencies
	@echo 1
